client/Routes.js, client/components/AdminRoute.js, client/components/auth/index.js, client/components/core/Login.js, package-lock.json
When user logs in as Admin it redirects to '/orgAdmin' route, if user tries to go to '/orgAdmin' without entering Admin into email field then they are redirected to '/' route
=> Added route protection for Admin route

.github/workflows/run-tests.yml, cloud-functions/README.md, cloud-functions/firebase.json, cloud-functions/firestore.rules, cloud-functions/functions/__tests__/auth.test.ts, cloud-functions/functions/__tests__/rules.test.ts, cloud-functions/functions/package.json
Created a set of [Cloud Firestore Security Rules](https://firebase.google.com/docs/firestore/security/get-started) (`cloud-functions/firestore.rules`) that determine who can read/write to which documents in our database.
I added extensive tests in `cloud-functions/functions/__tests__/rules.test.ts` to really make sure all bases were covered. Those tests should also provide a good guide for client developers to follow for accessing data on the frontend. Again, everything prefixed by `clientDb` and `clientAuth` is from the Firestore client sdk, which we can use in the react app.
=> Firestore rules

client/src/components/NavBar.js
I used "class" instead of "className" which causes react to log a warning. This change fixes that.
=> Fix react invalid property warning from navbar

.github/workflows/deploy.yml, permission-portal-frontend/scripts/deploy.sh
Updates the deploy script and deploy workflow for the prod environment.
A push to `dev` will deploy to staging and a push to `master` will deploy to prod.
Also added the `--only-show-errors` option to the S3 commands to suppress unnecessary logging in the action.
=> Add production environment

permission-portal-cloud-functions/firestore.rules, permission-portal-frontend/client/src/components/NavBar.js, permission-portal-frontend/client/src/screens/Settings.js, permission-portal-frontend/client/src/store/index.js
- revised My Settings so that you don't need to click the "save settings" button in order to save your profile image
- added a new collection in our firestore called `userImages` so that the app isn't downloading large amounts of useless image data (which is what would happen if we stored each image blob in the user document itself)
- updated rules to allow for reading/writing of `userImages` collection
- updated the store to handle all this new logic
This is the next iteration of @prabhuinbarajan 's work in this PR (now closed): https://github.com/covid19risk/permission-portal/pull/149
=> Navbar profile img revised

permission-portal-frontend/client/src/store/index.js
Persist the global `store` in `localStorage`.
closes https://github.com/covid19risk/permission-portal/issues/172
=> Persist store

permission-portal-frontend/client/src/screens/ManageTeams.js
Closes #197 
The error was caused by line 156, which was directly editing the model field. We don't need that line or the line after it, because `updateUserByEmail` invokes the `organizationMembersListener` (in `store/index.js`) which updates the user model. The `select` component is reactive, so it will update the `className` automatically when the user model is updated. 
I tested by activating and deactivating my user, and everything works as expected.
=> Fix Mobx Error on user status change

permission-portal-frontend/client/Styles/components/button.scss, permission-portal-frontend/client/Styles/screens/code_validations.scss, permission-portal-frontend/client/Styles/screens/delete_user_modal.scss
Closes #198 
Added a margin to the `progress-container` id in the delete user modal to match the margin of the button. Made sure the `progress-container` id is set in `button.scss` and not `code_validations.scss` since it is not used there and we will be redoing that page soon.
=> Add circular progress margin

frontend/client/Styles/screens/change_password_modal.scss, frontend/client/src/components/ChangePasswordModal.js, frontend/client/src/components/ResetPasswordModal.js, frontend/client/src/screens/Settings.js
Closes #244 
Adds `ResetPasswordModal` which is very similar to `ChangePasswordModal` (thanks @aidan-fitz !). After #243 is finished, we can abstract out what is the same between the 3 modals into a common base component. 
Changes to the `change image modal` component in `Settings` will be overrideen by #246, I just changed them here to avoid errors.
=> Reset Password (settings page)

CONTRIBUTING.md, frontend/client/Styles/screens/change_password_modal.scss, frontend/client/src/components/ChangePasswordModal.js, frontend/client/src/components/ForgotPasswordModal.js, frontend/client/src/components/PendingOperationButton.js, frontend/client/src/screens/Login.js, frontend/client/src/screens/Settings.js
Closes #109.
- Use `PendingOperationButton` whenever we need an `async` function, naked `<button>` elements otherwise. Note: `operation` prop must be an `async` function or return `Promise` (both are equivalent in JavaScript).
- Add `disabled` and `style` props to POB.
- Convert POB to use a `<button>` tag internally and have `button` and `disabled` CSS classes by default. This simplifies CSS a bit, but we still need to refactor the CSS to use fewer custom classes.
=> Unify buttons

frontend/.eslintrc.js, frontend/client/src/util/logging.js
Removes the rule `no-console: 0` except in `logging.js`.
Closes #122
=> Disable no-console only in logging.js

frontend/client/Styles/application.scss, frontend/client/Styles/components/profile_photo.scss, frontend/client/src/components/NavBar.js, frontend/client/src/screens/Settings.js
Fixes #285.
Changing the profile pic CSS from `object-fit: none` to `object-fit: cover` resizes the image to fill its parent element.
=> Use object-fit: cover

frontend/client/src/screens/404.js, frontend/client/src/screens/AccountBranding.js, frontend/client/src/screens/CodeValidations.js, frontend/client/src/screens/ManageTeams.js, frontend/client/src/screens/Settings.js
Refactored route blocking to be more consistent, and to account for isFirstTimeUser and passwordResetRequested && signedInWithEmailLink.
(I spent a bunch of time tinkering around in search for a more elegant solution consisting of composed higher order components (similar to `withStore`), but gave up when I started bumping into weird ES versioning issues with babel.)
closes https://github.com/covid19risk/permission-portal/issues/275
=> Refactor route blocking

frontend/client/Styles/application.scss, frontend/client/Styles/components/modal.scss, frontend/client/Styles/screens/change_role_modal.scss, frontend/client/src/components/ChangePasswordModal.js, frontend/client/src/components/ChangeRoleModal.js, frontend/client/src/screens/ManageTeams.js
Closes #273
`ChangeRoleModal` looks like:
To test: toggle a user's role between Org Admin and Validator to bring up the prompt, then click Confirm to ensure the role is changed or Cancel to exit.
=> Create bespoke ChangeRoleModal

frontend/client/Styles/screens/add_member_modal.scss, frontend/client/Styles/screens/change_password_modal.scss, frontend/client/src/components/AddMemberModal.js, frontend/client/src/components/ResetPasswordModal.js
Previously, on failure, add member modal looked whacko on small screens:
Fixed that by adding some inline styling logic.
closes https://github.com/covid19risk/permission-portal/issues/188
=> Modify Add Member modal to fit on smaller screens

.github/workflows/build-and-test.yml, .github/workflows/deploy.yml, cloud-functions/README.md, cloud-functions/functions/package-lock.json, cloud-functions/functions/package.json, cloud-functions/functions/secrets.sh, cloud-functions/functions/src/index.ts, config/functions.config.dev.js, config/functions.config.local.js, config/functions.config.prod.js, config/functions.config.staging.js, config/functions.config.test.js, frontend/client/Styles/screens/code_validations.scss, frontend/client/src/screens/CodeValidations.js, frontend/client/src/store/firebase.js, frontend/client/src/store/index.js, frontend/webpack.dev.js
The so-called cookie-server approach to integrating the verification server (VS) with the permission portal.
The idea is to have one user in the verification server for the whole permission portal. When a code is requested by a user from the frontend, the new cloud function `getVerficationCode` logs into the server as that user and gets a new code via http requests.
- The verification server running locally (instructions are [here](https://github.com/google/exposure-notifications-verification-server), using either CW firebase project or your own)
- A local firebase project for the permission portal that is set up correctly (so we don't mess up the dev project)
Picking up the last steps from the README of the exposure-notifications Repo linked above, create a user with email `**email**` …
=> Verification Server integration with cookie/session

cloud-functions/functions/__tests__/auth.test.ts, cloud-functions/functions/__tests__/config.ts, cloud-functions/functions/src/index.ts
All this talk about security testing in our meeting got me to thinking about whether we'd just exposed verification code generation to the entire world, which we had. This solves that.
Linter/formatter did a number on the `__tests__/auth.test.ts` file, but the substantive change is the test named `'getVerificationCode cannot be called without being authenticated'`.
=> Auth protect get verification code

cloud-functions/functions/src/index.ts, frontend/client/src/screens/CodeValidations.js, frontend/client/src/store/index.js
I've structured the frontend/backend so that it passes a hardcoded
```javascript
{
testType: 'confirmed',
testDate: new Date().toJSON().substring(0, 10),
}
```
from the frontend, preparing us for passing values taken from the interface (currently blocked by Figma v4).
=> Pass testType and testDate from the frontend to getVerificationCode

cloud-functions/firestore.rules, cloud-functions/functions/__tests__/auth.test.ts
The test to look at is called `'An attacker cannot create an account and then quickly create their own record in /users table before onCreate has time to run and delete them'`, the rest of the changes are formatting differences (argh!).
I thought up a potential attack where a user creates an account (in Firebase auth) through the client library, then quickly signs in and creates their own user document before our `onCreate` hook has time to run and delete their account. As it turns out, our `isAdmin()` rule protects against this, but I added a test to assure this is enforced.
=> Sanity check on signup protection

frontend/client/index.js, frontend/package-lock.json, frontend/package.json
[Sentry](https://sentry.io/) is an error reporting service Jeff suggested we use.  See a screen capture video I made [here](https://www.loom.com/share/989be1deb6434003a54ca10895e2a913) that describes how this works.
There are some more customized things we can do that may be desirable - such as some custom handling logic for what to display if the user errors out for some reason so it isn't just a blank white screen.  Maybe just trigger a refresh?  Or show a 'contact Covid Watch' message?  Not sure.  More info on this in the Sentry docs about ["error boundaries"](https://docs.sentry.io/platforms/javascript/react/#error-boundaries).
Suggestions welcome for what error boundaries to set up, if any, at this stage.  Otherwise, this is probably ok to merge now and we can improve the workflow …
=> Add Sentry error reporting

frontend/client/src/screens/CodeValidations.js, frontend/client/src/util/time.js
Some minor workflow updates to the `CodeValidations.js` to maintain dates between today and 14 days ago.
Updates:
1) show Toast msg on choosing date out of bounds
2) do not allow code generation until a valid date is chosen
3) return to the code format 000-000-00 instead of 0000-0000
Preview:
=> V4 code validations dates

cloud-functions/functions/src/index.ts
Closes #371 
1) set all sending email addresses to noreply@covidwatch.org
2) fix the 'recieve' typo to 'receive'
3) remove any mention of "Covid Watch Permission Portal" to just "Covid Watch Portal"
=> SendGrid email adjustments

frontend/client/Styles/screens/manage_teams.scss
Resolves   #376 
Improved padding on select elements to make them fill their container better, made down arrows clickable.  
Image preview of the change:
=> Manage Members/Add Members down arrow fix

frontend/client/src/screens/Login.js
I saw this error happening in staging reported in Sentry logs, which was worrisome so I investigated and found a small syntax error in `Login.js` using `this.errorToast.show()` instead of `this.errorToast.current.show()`.  I also adjusted how state is set so it isn't set directly which is bad form and can lead to bugs (more on why it's bad form [here](https://daveceddia.com/why-not-modify-react-state-directly/) if curious).
=> Resolve magic link syntax error

frontend/client/src/screens/CodeValidations.js
=> remove hyphens from code in code generation page

frontend/package-lock.json, frontend/package.json
`file-system` contains [a vulnerability](https://www.npmjs.com/advisories/1502) that hasn't been addressed in over 4 months. Since we're not using it anyway, this vulnerability doesn't affect us, but at least it won't bother `npm audit`.
=> Remove unused package file-system

frontend/client/index.js, frontend/client/src/store/firebase.js
I'm pretty sure that this will achieve what I have in mind.  It seems to work in local environment (see screenshot below) but I want to test in staging environment also.
If there is a better way to import the environment string to `index.js` better than declaring a global window variable, feel free to suggest.  I made sure that this variable is only a string like "staging" or similar so doesn't expose any vulnerabilities or sensitive info.
Screenshot from a local environment in Sentry interface:
=> add sentry environment to label and filter error reports better

frontend/client/src/components/AddMemberModal.js, frontend/client/styles/screens/change_password_modal.scss
Simple change.  Closes #393 
The Recover Password modal header spacing was already resolved by another PR and is live in staging corrected currently.
See visual preview of AddMemberModal: 
And adjustment of `<h2>` to `<h3>` for ChangePasswordModal to be consistent w other modals.  The result:
=> Modal header consistency adjustments

frontend/client/src/components/ChangeRoleModal.js, frontend/client/src/components/ChangeStatusModal.js, frontend/client/src/components/ForgotPasswordModal.js, frontend/client/src/components/PendingOperationButton.js, frontend/client/src/screens/Settings.js, frontend/client/styles/components/profile_photo.scss, frontend/client/styles/screens/add_member_modal.scss, frontend/client/styles/screens/change_password_modal.scss, frontend/client/styles/screens/change_role_modal.scss, frontend/client/styles/screens/change_status_modal.scss, frontend/client/styles/screens/login.scss
Closes #364 
My goal with this was to use a consistent `progress-container` class as a wrapper for all `PendingOperationButtons` to create one consistent solution for the loading graphic to not displace other elements vertically when loaded.  However I quickly realized that this wouldn't actually work for all cases (like when there are two buttons beside each other and one is a Cancel button that is NOT a `<PendingOperationButton>` (this happens a lot in the modals).  
So I ended up doing a hodge podge of mostly CSS changes here and there to prevent the jerky effect when the loading graphic loads on the page in any context.
Please test thoroughly all buttons and `<PendingOperationButton>` cases to make sure nothing is clearly messed up.  I think I got them all (including the one that …
=> Loading graphic doesn't move elements when loaded

frontend/client/src/components/NavBar.js
I made the unilateral decision to keep "Account Settings" to "Mobile App Settings", bc I thought "Account Settings" would be confusing next to "My Settings".  Either way, I imagine we will change this in the future to be more clear once we have a clearer function for the "Account Settings" page.
Otherwise this matches v4 Figma for the hamburger menu options.
=> update the hamburger menu option names to match v4 better

config/functions.config.prod.js, config/functions.config.staging.js
As the permissions URLs are no longer available via AWS.  I maybe should have set up forwarding but in lieu of that modifying the sendgrid URL here.
=> remove permissions urls in functions for sendgrid email

frontend/client/src/components/ResetPasswordModal.js
Resolves #416  
Reset password modal now rejects your new password if it is the same as the inputted current password. Updated `onChange` function of `ResetPasswordModalBase` to use a switch statement for better readability/efficiency.  
Note: this does not fix issues associated with the "forgot your password" reset via the login page (you are able to use the same password as the previous).
=> Reset Password Fix

frontend/client/src/components/AddMemberModal.js
Resolves #417  
Adding a member now clears the state so their information does not appear again when opening modal. Closing a modal while in progress of adding a member now resets state as well.
=> Closing Add Member Modal Now Resets State

.github/workflows/deploy.yml, frontend/scripts/deploy.sh
Closes #415 
Updates the deploy script to upload the favicon to AWS S3.
Reviewing `deploy.sh` I realized we're uploading `index.html` to S3 every push, which isn't necessary as it never changes at this point. And I think we're charged (a very small amount) for each upload. So, `deploy.sh` now only uploads `index.html` and `favicon.ico` to S3 if they were modified in the previous commit. Our usual strategy is to merge a PR into dev/master, so this really checks if `index.html` and `favicon.ico` were changed in the previous PR. Needed to update the action workflow to get the last 2 commits instead of the last 1. 
As this is a change to the deploy script/workflow, we'll want to watch closely for a PR or 2 to make sure everything still works.
=> Deploy script update for favicon

frontend/client/src/screens/CodeValidations.js, frontend/client/src/util/time.js, frontend/client/styles/screens/code_validations.scss
- cleaned up time.js a bit 
- created `localStringToZeroUTCOffsetString` to convert local yyyy-mm-dd datestrings to yyyy-mm-dd datestrings with a zero UTC offset, which we now use before sending the date to the server.
Makes use of [toISOString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
> The toISOString() method returns a string in simplified extended ISO format (ISO 8601), which is always 24 or 27 characters long (YYYY-MM-DDTHH:mm:ss.sssZ or ±YYYYYY-MM-DDTHH:mm:ss.sssZ, respectively). The timezone is always zero UTC offset, as denoted by the suffix "Z".
- Changed the subtext of the Symptom Onset Date input to "Timezone set to <default timezone>" i.e.
closes https://github.com/covidwatchorg/portal/issues/443
=> Convert time before sending to getVerificationCode

frontend/client/src/components/NavBar.js, frontend/client/src/store/firebase.js, frontend/client/src/store/index.js, frontend/client/src/store/model.js
Fixes a bug where a user could request a password reset, click the magic link, get the supposed-to-be-un-dismissible reset modal, but then refresh the page and be logged in without ever actually resetting the pwd (see the video link in https://github.com/covidwatchorg/portal/issues/450)
Also fixes the NavBar weirdness (shown at the end of the video linked in https://github.com/covidwatchorg/portal/issues/450), so that at the points during the pwd reset where the user is technically logged in but hasn't completed the process, the navbar appears to them the same as if they were logged out.
closes https://github.com/covidwatchorg/portal/issues/450
=> Fix "reset password workflow logs user in with magic link without resetting password"

frontend/security.txt
A request from @whaber to add this similar to what we just added to the website: https://covidwatch.org/security.txt.
Just adding this file to the `/static` folder so it shouldn't affect any other code in any way.
=> add bug bounty .txt file to /static

frontend/client/styles/screens/code_validations.scss
Fixed the issue that made Safari Radio Buttons look distorted at certain zoom levels. Removed the line transform:scale(1.23), which was causing the issue and adjusted the height/width of the buttons, and the margin-left to match the previous style. The radio buttons will look different in various browsers unless we add a significant amount of custom styling to normalize it across all browsers. View this link for reference --->[Link][https://www.456bereastreet.com/lab/styling-form-controls-revisited/radio-button/](url).
=> Issue #409 Radio Buttons

frontend/client/src/store/index.js, frontend/client/src/store/model.js
closes https://github.com/covidwatchorg/portal/issues/423
Sets Firebase auth state-persistence to `NONE` and removes `sessionStorage` caching of the mobx `store` for non-development environments. We're keeping these for dev, since otherwise every time the webpack dev server hot-reloads you get logged out, which makes development extremely tedious.
To test:
- `npm run start:test # start the dev server with NODE_ENV=test`
- Login is admin@soylentgreen.com
- Refresh the page and see that you're logged out
- Ctrl-C to stop the dev server
- `npm run start:dev # start the dev server with NODE_ENV=development`
- Login is admin@soylentgreen.com
- Refresh the page and see that you're still logged in
=> Change auth state persistence to NONE

frontend/client/index.js, frontend/client/src/screens/Login.js, frontend/client/src/screens/Settings.js, frontend/client/src/store/index.js, frontend/package-lock.json, frontend/package.json
closes https://github.com/covidwatchorg/portal/issues/481
Also removes some unnecessary logging. A truly motivated attacker could likely still figure out how to modify store state directly, i.e. https://blog.jscrambler.com/the-most-effective-way-to-protect-client-side-javascript-applications/. However given the very limited damage they could do (they could only see protected routes client-side, not access/modify protected data, I think this is enough protection for the time being.
=> Disable react dev tools

frontend/client/styles/components/navbar.scss
Resolves #483  
Changed font size to 1.2em to scale better on smaller devices.
New Iphone 5/5s menu view  
Iphone X view
=> Mobile menu text size fix

frontend/client/src/screens/Login.js, frontend/client/src/screens/ManageTeams.js, frontend/client/styles/components/navbar.scss, frontend/client/styles/screens/add_member_modal.scss, frontend/client/styles/screens/manage_teams.scss
Members grid hidden on mobile until further refactoring can be made. Still able to add members, displays message to use desktop if you want to see members grid. Pic below:  
Also added link to manage members screen back to mobile nav menu.
=> Temporary Manage Members Mobile Screen for Friday

frontend/client/src/screens/Settings.js
closes #490 
Note that the user is able to delete all characters from the `firstName` and `lastName` fields but the store is only altered if the field has one or more characters.  Meaning that a user can remove all characters, see an error message, but the name that is saved is a single character if they navigate away from the page.
I played with a few options like forcing a single character to remain in the input fields but this seemed like a bad UX if the user for some reason wants to delete all characters and start over, it prevents them from doing so and is a little jerky.
=> prevent name change save of one char

frontend/client/src/screens/CodeValidations.js, frontend/client/src/screens/Login.js
Closes #435 
The bug here occurs only when  the same date is selected for 2 tests in a row. In `resetState()`  we set call `reset()` on the date picker form. Calling `reset()` clears the date input box, but does not actually reset the `value` stored in the input element. So, the second time the date is selected, it is not registered a change in the input element. Here, we log the value of `symptomDate` in `genNewCode()`. 
The easy fix is to set `value={symptomDate}` in the props of the `<input>` tag. This ensures the value in the input component is always `symptomDate`, which is set to an empty string when the reset button is pressed. However, this caused weird behavior when typing in new dates.
So, instead we manually reset the value of the input component to an empty string in …
=> Date Picker Bug

frontend/client/src/screens/Settings.js, frontend/client/styles/screens/settings.scss
Resolves #497  
Breakpoint for items moving around happens a bit earlier to prevent overlap. Only adjusted material-ui grid and moved media query for items aligning center to `<desktop` instead of `<=phone`. Gif shown below:
=> My settings page overlap fix on smaller screen sizees

frontend/client/__tests__/code_validations.test.js, frontend/client/src/screens/CodeValidations.js, frontend/client/src/util/time.js, frontend/client/styles/screens/code_validations.scss, frontend/package-lock.json, frontend/package.json
closes #491 #410 
Safari desktop [doesn't support a calendar picker](https://stackoverflow.com/questions/35682138/html5-date-picker-doesnt-show-on-safari) unfortunately (lame).
More robust solution is to populate a calendar picker no matter the browser, which is done here using [ReactDatePicker](https://reactdatepicker.com/).  I tested the whole workflow on Safari and all works as expected (same as Chrome).
Note that Safari mobile has a much better date picker UX.  I was concerned about this as it seems many users will be on mobile and Safari is the default browser for iPhones.  No need to adjust for this, thankfully (see screenshot below from my own iPhone on Safari):
=> Custom Safari desktop date picker

.github/workflows/build-and-test.yml, .github/workflows/deploy.yml, config/functions.config.dev.js, config/functions.config.local.js, config/functions.config.prod.js, config/functions.config.staging.js, config/functions.config.test.js
Updating the verification server urls to distinguish between dev and prod. All infrastructures point to https://dev.adminapi.verification.covidwatch.org, except for prod which points to https://adminapi.verification.covidwatch.org.
Hardcodes the url strings rather than using environment variables, since they're not secret.
Also updates the test config to use the dev VS url and grab the API key from the env, in preparation for future integration test development.
NOTE-to-self: after this is merged would be a good time to go through our Github secrets and clean up some cruft.
=> Update VS urls

frontend/client/__tests__/code_validations.test.js, frontend/client/src/screens/CodeValidations.js
See [this Asana task](https://app.asana.com/0/1184720811395617/1189146139134603/f).  DM me on Slack if you can't access Asana.
Copying the text from Asana just in case ppl can't access it.  This is a task created by Sameer.  Basically with this PR users can more quickly generate codes as the single action they can complete in Portal.
##From Asana:
"We only support positive diagnosis.
Having the other two options is creating user confusion.
lets hide the 2nd & 3rd options.
Make 1st one be selected by default
In October we will need to turn it back on when the app actually starts supporting it."
=> refactor reset form workflow to always have radio value be confirmed

frontend/client/src/screens/CodeValidations.js
Resolves this [Asana task ](https://app.asana.com/0/1188301658055194/1189443161936967/f).  
`symptomDateYYYYMMDD` was being set to `null` instead of `''` (empty string), which was conflicting with the logic in function `genNewCode`.
=> resolve no code generated after deleting date

frontend/scripts/deploy.sh
As noted in #532, with the Babel updates, the `polyfill.js` file is no longer included in the `dist/` directory (`dist/` is generated by `npm run build`). However, if you look in the S3 bucket for the portal `polyfill.js` is still there! This is because we update the `dist/` folder in S3 with the `aws s3 sync` command. By default `sync` apparently does not remove files in the bucket which were removed in source directory. So, even though `pollyfill.js` was removed from `/dist`, it remained in the bucket. So, we add the `--delete` flag to the `sync` command, which deletes any files in the bucket that are not in the source directory. Docs [here](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html). The final effect is that the source directory (`dist/`) and the S3 bucket are …
=> Add "delete" option to AWS sync
