- README.md
Added @ibeckermayer and my github links to contact info
> Update contact section in readme

- cloud-functions/.firebaserc
- cloud-functions/README.md
- cloud-functions/functions/.gitignore
- cloud-functions/functions/__tests__/auth.test.ts
- cloud-functions/functions/package-lock.json
- cloud-functions/functions/package.json
- cloud-functions/functions/reset-dev-infrastructure.js
- cloud-functions/functions/src/index.ts
See the diff in the `README.md`
> Add dev infra

- client/Routes.js
- client/Styles/components/footer.scss
- client/src/components/Footer.js
Logo conditionally renders based on the page. It will render on all pages but the login page.
> Added logo to footer

- .eslintrc.js
- .prettierrc
- client/Firebase.js
- client/index.js
- client/src/screens/Login.js
- client/src/util/AdminRoute.js
- client/src/util/auth.js
- cloud-functions/functions/reset-dev-infrastructure.js
- package-lock.json
- package.json
Barebones implementation of login integration. I didn't put any thought into whether this is the correct state management architecture for the app, I just used what was there as a platform.
Note that the logout functionality is also not implemented, [created an issue](https://github.com/covid19risk/permission-portal/issues/53) so we don't forget.
The dev infra has two organizations and 4 users:
Orgs:
- Soylent Green
- Initech
Users:
- admin@soylentgreen.com
- user@soylentgreen.com (non-admin user)
- admin@initech.com
- user@initech.com (non-admin user)
All the users have their password == to their email
> Integrate login

- cloud-functions/functions/package-lock.json
- cloud-functions/functions/package.json
- cloud-functions/functions/src/index.ts
`onCreate` now sends new users a welcome email imploring them to change their password. I've tested that it works manually on the dev infrastructure, which can be done by creating a new user with your own email address and checking that you receive the email, following the link in the email and changing your password, and then logging in with your updated password.
> Added and tested a welcome email

- client/src/components/NavBar.js
- client/src/constants/roles.js
- client/src/screens/CodeValidations.js
- client/src/screens/Login.js
- client/src/screens/Settings.js
> Non admin flow complete

- permission-portal-cloud-functions/functions/__tests__/auth.test.ts
- permission-portal-cloud-functions/functions/src/index.ts
- permission-portal-frontend/client/src/components/Firebase/firebase.js
- permission-portal-frontend/client/src/components/RoleSelector.js
- permission-portal-frontend/client/src/screens/AccountBranding.js
- permission-portal-frontend/client/src/screens/AddMemberModal.js
- permission-portal-frontend/client/src/screens/ManageTeams.js
- permission-portal-frontend/client/src/store/index.js
- permission-portal-frontend/package.json
Biiiig PR with a lot of stuff going on in the backend, primary thing to review is that Add User indeed works (test this manually by adding your own email address). @fordacious check out the frontend code, I modified `AddMemberModal` primarily.
closes #103
> Modify welcome email

- permission-portal-cloud-functions/firestore.rules
- permission-portal-cloud-functions/functions/__tests__/rules.test.ts
fixes to allow users from escalating privileges.
> firestore security

- permission-portal-frontend/client/src/screens/Login.js
> Add login failure toast

- permission-portal-frontend/client/src/components/Toast.js
- permission-portal-frontend/client/src/screens/AccountBranding.js
- permission-portal-frontend/client/src/screens/CodeValidations.js
- permission-portal-frontend/client/src/screens/Login.js
- permission-portal-frontend/client/src/screens/ManageTeams.js
- permission-portal-frontend/client/src/screens/Settings.js
To avoid code duplication, we use the `Toast`'s state to control whether it is open or closed.
Closes #192 
Closes #181
> Use component state to control visibility of Toasts

- permission-portal-cloud-functions/functions/__tests__/auth.test.ts
- permission-portal-cloud-functions/functions/src/index.ts
closes https://github.com/covid19risk/permission-portal/issues/201
Also took the opportunity to delete now deprecated `validate` cloud func.
> fixing uppercase email address bug

- permission-portal-cloud-functions/.firebaserc
- permission-portal-cloud-functions/functions/package-lock.json
- permission-portal-cloud-functions/functions/package.json
- permission-portal-cloud-functions/functions/reset-infrastructure.js
- permission-portal-cloud-functions/functions/src/index.ts
Updated `permission-portal-cloud-functions/functions/reset-infrastructure.js` to allow us to reset the database and upload an arbitrary number of sample users, in preparation for pagination development.
Tested that it works on a private instance of Firebase infrastructure, so as not to screw with dev. Once it's merged, somebody should run it and upload ~10k users to the dev infra
> Populate db

- permission-portal-cloud-functions/firebase.json
- permission-portal-cloud-functions/firestore.indexes.json
- permission-portal-cloud-functions/functions/src/index.ts
- permission-portal-frontend/client/src/store/index.js
Closes #191
This sorts entries in the member table by last name, then by first name.
> Order members by last name, then by first name

- permission-portal-frontend/client/src/constants/roles.js
> updated strings

- permission-portal-frontend/client/Styles/screens/settings.scss
- permission-portal-frontend/client/src/screens/Settings.js
Closes #222 
Also lines up Profile Photo column and the My Settings header.
> Add "Changes Automatically Saved" to settings page

- permission-portal-frontend/client/src/screens/Settings.js
> Add dummy password box

- permission-portal-cloud-functions/functions/package-lock.json
- permission-portal-frontend/package-lock.json
Fixes https://github.com/covid19risk/permission-portal/network/alert/permission-portal-cloud-functions/functions/package-lock.json/websocket-extensions/open
> updating websocket extensions

- SECURITY.md
This will be replaced with something better in the future, but is ok to start with this.
> Adding initial security policy

- frontend/client/Styles/components/navbar.scss
- frontend/client/assets/menu.svg
- frontend/client/src/components/NavBar.js
Closes #226
I created the divider line in CSS and imported the menu icon as a separate SVG (thanks Vic for getting me the correct version!). I also created the correct amount of whitespace around the navbar.
> Use correct menu icon and divider

- frontend/client/src/screens/ManageTeams.js
> updated arrows on manage teams

- frontend/client/Styles/screens/add_member_modal.scss
- frontend/client/Styles/screens/login.scss
To review: See that login screen and add member modal look ok.
> fixing some wonkiness on the login screen and add_member_modal

- frontend/client/src/screens/CodeValidations.js
closes https://github.com/covid19risk/permission-portal/issues/251
> removing tool tip and updating subtext

- cloud-functions/functions/src/index.ts
- frontend/client/src/screens/ManageTeams.js
- frontend/client/src/store/index.js
Also made the Manage Teams "Reset Password" link send the branded recovery email.
closes https://github.com/covid19risk/permission-portal/issues/270
closes https://github.com/covid19risk/permission-portal/issues/274
> Update recover password email

- cloud-functions/functions/src/index.ts
Updating new user email to have a sign in with email link
closes https://github.com/covid19risk/permission-portal/issues/272
> updating new user email to have a sign in with email link

- frontend/client/Styles/screens/manage_teams.scss
- frontend/client/src/components/RoleSelector.js
- frontend/client/src/screens/ManageTeams.js
- frontend/client/src/store/index.js
- frontend/client/src/store/model.js
Reintroducing client-side handling of pagination. Performance should be good enough for now, we'll cross that bridge when/if we come to it (i.e. an organization with thousands of users)
closes https://github.com/covid19risk/permission-portal/issues/287
> Reintroduce pagination

- frontend/client/src/store/index.js
> changing blob to imageBlob to match backend

- frontend/client/Styles/components/button.scss
- frontend/client/Styles/components/modal.scss
- frontend/client/Styles/screens/404.scss
- frontend/client/Styles/screens/add_member_modal.scss
- frontend/client/Styles/screens/branding.scss
- frontend/client/Styles/screens/change_password_modal.scss
- frontend/client/Styles/screens/change_role_modal.scss
- frontend/client/Styles/screens/forgot_password_modal.scss
- frontend/client/Styles/screens/login.scss
- frontend/client/Styles/screens/manage_teams.scss
- frontend/client/Styles/screens/settings.scss
- frontend/client/src/components/ChangePasswordModal.js
- frontend/client/src/components/ChangeRoleModal.js
- frontend/client/src/components/PendingOperationButton.js
- frontend/client/src/components/ResetPasswordModal.js
- frontend/client/src/screens/404.js
- frontend/client/src/screens/AccountBranding.js
- frontend/client/src/screens/ManageTeams.js
- frontend/client/src/screens/Settings.js
Closes #253
Will do modals in a follow-up PR.
> Refactor SCSS for buttons

- frontend/package.json
Partially a test to see if TSLint fails on all branches or just mine.
> Harmonize package.json license to Apache 2.0

- cloud-functions/functions/src/index.ts
- frontend/client/src/screens/Login.js
> Error handling for magic links

- frontend/client/Styles/screens/branding.scss
- frontend/client/src/screens/AccountBranding.js
Simple change, nothing complex happening here.
> remove the link on AccountBranding.js

- frontend/client/src/screens/Settings.js
> Fix add image icon is huge again

- frontend/client/src/screens/AccountBranding.js
- frontend/client/src/screens/Login.js
Resolves #366  
Login Failure Toast now shows correct error instead of empty message.
> Login Failure Toast Fix

- frontend/client/src/components/NavBar.js
> Profile picture now links to /settings

- frontend/client/src/screens/CodeValidations.js
Simple text update.  Closes #375
> change 'Test Date' to 'Symptom Onset Date'

- cloud-functions/functions/package-lock.json
- cloud-functions/functions/package.json
- frontend/client/src/screens/ManageTeams.js
- frontend/package-lock.json
- frontend/package.json
> Upgrade ts-jest to version 26.1.3, concurrently to version 5.2.0

- frontend/client/src/screens/Login.js
- frontend/client/src/screens/ManageTeams.js
- frontend/client/src/screens/Settings.js
- frontend/client/src/store/index.js
- frontend/package-lock.json
- frontend/package.json
Resolves #365   
Added loading spinner during upload and used a compression library to ensure we don't have any errors uploading files smaller then 10MB. The best ratio for the compression options I found was 0.6 max MB with max height/width set to 900. Feel free to test out more, but going over that usually lead to problems with some larger files.
> Profile Picture Upload Fixes

- cloud-functions/functions/src/index.ts
Closes https://github.com/covidwatchorg/portal/issues/377 (see comment)
> remove auto sign in link from new user email

- frontend/client/index.js
- frontend/client/src/components/Toast.js
- frontend/client/src/screens/Login.js
- frontend/client/src/store/firebase.js
Closes #406 
Some linter fixes snuck in, but I only made the changes in `Login.js`
> Make login box a form

- cloud-functions/functions/reset-infrastructure.js
- config/firebase.config.local.js
closes https://github.com/covidwatchorg/portal/issues/368
> adding concerned citizen warning to config.local and updating reset-infra

- frontend/index.html
Small change to pathing to favicon in `index.html`, not sure how to test in staging/prod
> Favicon Production/Staging Fix

- frontend/client/src/components/Footer.js
Closes #367 .  Still waiting on some clarification on the Terms of Service document so this will be a draft for now until that is finalized.  Then should be quick merge given minimal adjustments happening here
> add footer links (Privacy Policy, TOS)

- frontend/package-lock.json
- frontend/package.json
Resolves #359 - upgrade elliptic to 6.5.3 per [npm advisory 1547](https://www.npmjs.com/advisories/1547)
Resolves #357 - upgrade dot-prop to 5.2.0 per [npm advisory 1213](https://www.npmjs.com/advisories/1213)
> Upgrade nodemon and elliptic

- frontend/client/src/components/Footer.js
- frontend/index.html
Tried a different fix, adding `?` to the end of the favicon path
> Favicon Fix

- cloud-functions/functions/package-lock.json
- cloud-functions/functions/package.json
This resolves the vulnerability in `yargs-parser` on the server side (dev dependency only).
> Upgrade node-env-run to 4.0.1 on cloud-functions

- cloud-functions/functions/firebase-repl.js
- config/firebase.config.prod.js
- frontend/client/src/store/firebase.js
- frontend/index.html
Request from UofA (and internally known for a long time) to have some analytics capabilities within Portal.  This should enable Firebase Analytics so we can begin to capture user data in a more structured way to iterate from there.
For now, any analytics capability will be through the Firebase UI and NOT Portal UI.
> add firebase analytics sdk for production portal

- cloud-functions/functions/package-lock.json
- cloud-functions/functions/package.json
- frontend/package-lock.json
- frontend/package.json
Upgraded dev dependencies with high-severity vulns: webpack and firebase-tools.
> Upgrade dev dependencies

- .github/workflows/deploy.yml
> Deploy to Firebase dev on push to dev branch

- frontend/client/__tests__/navbar.test.js
- frontend/client/src/components/NavBar.js
closes https://github.com/covidwatchorg/portal/issues/479
See the bug in [this video](https://asrivastava-lwolf.tinytake.com/tt/NDUzMjE2OV8xNDM2MzYzNQ) and see that this updated design fixes it. FTR, a similar bug could be triggered by clicking the image avatar to navigate to the settings page.
> Fix navigation menu

- frontend/client/src/screens/Login.js
- frontend/client/src/screens/Settings.js
- frontend/client/styles/screens/settings.scss
Inputs originally were in a weird order, adjusted so now they make more sense. Desktop view the same. Picture below:
> Changed order of inputs on my settings page for mobile view

- frontend/client/__tests__/__snapshots__/footer.test.js.snap
- frontend/client/src/components/Footer.js
- frontend/client/src/util/time.js
Closes #509 
Simple fix just adding an if statement if the hour time is 0, set it to 12.  I think that should solve it.
> solve code expire hour time being 0 when it should be 12

- frontend/client/__tests__/__snapshots__/navbar.test.js.snap
- frontend/client/src/components/NavBar.js
> Include prefix in navbar
